apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: default
spec:
  type: LoadBalancer
  selector:
    app: elasticsearch
  ports:
  - name: http
    port: 80
    targetPort: 9200
    protocol: TCP
